# 线上配置文件
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teammatch?serverTimezone=Asia/Shanghai
    username: root
    password: Ab123456
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    database: 1
    port: 6379
    host: localhost
server:
  address: 0.0.0.0
  port: 8080